### ISSUE TITLE
Fit artboard height not working as expected

### ISSUE THREAD

**Issue by pkvdesigns** [getflourish/Sketch-Mate#38]
Hi,

I recently updated the Sketch Mate plugins and noticed that the behaviour of the Fit artboard height plugin changed. In the previous version I used I could hit shortcut when selecting any element in an artboard and the artboard height would be adjusted.

In the newest version the shortcut only works when you have the artboard itself selected. 

It would be quicker to be able to hit the shortcut on any element within the artboard.

Hope you're able to fix this. If it's not clear let me know.

Best regards,

PK Vrieswijk

**Comment by mikeprecious** [comment]
+1 Really appreciate the Fit Artboard Height function.

**Comment by mikeprecious** [comment]
Any word on if the Fit Artboard Height function will be back up and running again?

**Comment by getflourish** [comment]
@mikeprecious I restored the old behavior. This broke because the need to handle multiple artboards at once came up. It is now possible to either have a layer selected => then the plugin crops the artboard that the layer is on. Or you can select multiple artboards which then all are cropped at once.

**Comment by getflourish** [comment]
![artboards](https://cloud.githubusercontent.com/assets/183989/21939612/e172793c-d9c0-11e6-80cf-cf00cbaf0a5d.gif)
